name=input("Your name:")
out_file=open("name.txt", 'w')
print(f"{name}",file=out_file)
out_file.close()
out_file=open("name.txt", 'r')
contents=out_file.read()
print(contents)
out_file.close()
in_file=open("numbers", 'r')
num1=int(in_file.readline())
num2=int(in_file.readline())
print(num1+num2)
in_file.close()
